AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >-
  A SAM CLI template for a single-endpoint Hello World Lambda function in Scala
Resources:
  HelloScalaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AWSLambdaScala
      Description: Example Lambda function in Scala
      Runtime: java8
      Handler: example.JavaHandler
      CodeUri: target/scala-2.13/aws-lambda-scala.jar
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          env: staging
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /
            Method: POST

Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"